import { IntakeDef } from "../engine/types";

export const adoptionIntake: IntakeDef = {
  intakeType: "adoption",
  title: "Client Intake: Adoption",
  description: "Information we need to guide your adoption matter.",
  steps: [
    {
      id: "your-info",
      title: "Your Information",
      fields: [
        { id: "yourFirstName", label: "First name", type: "text", required: true },
        { id: "yourMiddleName", label: "Middle name", type: "text" },
        { id: "yourLastName", label: "Last name", type: "text", required: true },
        { id: "yourBirthName", label: "Birth/Maiden name", type: "text" },
        { id: "yourStreet", label: "Street address", type: "text" },
        { id: "yourCity", label: "City", type: "text" },
        { id: "yourState", label: "State", type: "text" },
        { id: "yourZip", label: "Zip code", type: "text" },
        { id: "yourCounty", label: "County", type: "text" },
        { id: "yourCountyDuration", label: "How long in this county?", type: "text" },
        { id: "yourHomePhone", label: "Home phone", type: "tel" },
        { id: "yourCellPhone", label: "Cell phone", type: "tel" },
        { id: "yourDob", label: "Date of birth", type: "date" },
        { id: "yourPlaceOfBirth", label: "Place of birth", type: "text" },
        { id: "yourSsn", label: "SSN", type: "text" },
        { id: "yourDriversLicense", label: "Driver's license number", type: "text" },
        { id: "yourDriversLicenseState", label: "Issuing state", type: "text" },
        { id: "yourAutoMake", label: "Current automobile make", type: "text" },
        { id: "yourAutoModel", label: "Current automobile model", type: "text" },
        { id: "yourAutoColor", label: "Current automobile color", type: "text" },
        { id: "yourAutoYear", label: "Current automobile year", type: "text" },
        { id: "yourEmployerName", label: "Employer name", type: "text" },
        { id: "yourEmployerAddress", label: "Employer address", type: "text" },
        { id: "yourOccupation", label: "Occupation", type: "text" },
        { id: "yourAnnualIncome", label: "Approximate annual income", type: "text" },
        { id: "yourWorkPhone", label: "Work phone", type: "tel" },
        { id: "yourSafeEmail", label: "Secure/safe email address", type: "email" },
        {
          id: "yourInvoiceEmailOk",
          label: "Email monthly invoices/billing statements as PDF instead of mail?",
          type: "radio",
          options: [
            { label: "Yes", value: "yes" },
            { label: "No", value: "no" },
          ],
        },
        { id: "yourPreferredMailing", label: "Preferred mailing address", type: "text" },
        { id: "yourBillingAddress", label: "Billing address (if different)", type: "text" },
      ],
    },
    {
      id: "spouse-info",
      title: "Spouse Information",
      fields: [
        { id: "spouseFirstName", label: "First name", type: "text" },
        { id: "spouseMiddleName", label: "Middle name", type: "text" },
        { id: "spouseLastName", label: "Last name", type: "text" },
        { id: "spouseBirthName", label: "Birth/Maiden name", type: "text" },
        { id: "spouseStreet", label: "Street address", type: "text" },
        { id: "spouseCity", label: "City", type: "text" },
        { id: "spouseState", label: "State", type: "text" },
        { id: "spouseZip", label: "Zip code", type: "text" },
        { id: "spouseCounty", label: "County", type: "text" },
        { id: "spouseCountyDuration", label: "How long in this county?", type: "text" },
        { id: "spouseHomePhone", label: "Home phone", type: "tel" },
        { id: "spouseCellPhone", label: "Cell phone", type: "tel" },
        { id: "spouseDob", label: "Date of birth", type: "date" },
        { id: "spousePlaceOfBirth", label: "Place of birth", type: "text" },
        { id: "spouseSsn", label: "SSN", type: "text" },
        { id: "spouseDriversLicense", label: "Driver's license number", type: "text" },
        { id: "spouseDriversLicenseState", label: "Issuing state", type: "text" },
        { id: "spouseAutoMake", label: "Automobile make", type: "text" },
        { id: "spouseAutoModel", label: "Automobile model", type: "text" },
        { id: "spouseAutoColor", label: "Automobile color", type: "text" },
        { id: "spouseAutoYear", label: "Automobile year", type: "text" },
        { id: "spouseHeight", label: "Height", type: "text" },
        { id: "spouseWeight", label: "Weight", type: "text" },
        { id: "spouseHairColor", label: "Hair color", type: "text" },
        { id: "spouseEyeColor", label: "Eye color", type: "text" },
        {
          id: "spouseGlasses",
          label: "Glasses?",
          type: "radio",
          options: [
            { label: "Yes", value: "yes" },
            { label: "No", value: "no" },
          ],
        },
        { id: "spouseEmail", label: "Email address", type: "email" },
        { id: "spouseRace", label: "Race", type: "text" },
        { id: "spouseEmployerAddress", label: "Place & address of employment", type: "text" },
        { id: "spouseOccupation", label: "Occupation", type: "text" },
        { id: "spouseAnnualIncome", label: "Approximate annual income", type: "text" },
      ],
    },
    {
      id: "marriage-info",
      title: "Marriage Information",
      fields: [
        { id: "marriageDate", label: "Marriage date", type: "date" },
        { id: "marriagePlace", label: "Place of marriage (city/state)", type: "text" },
        { id: "marriageCounty", label: "County", type: "text" },
      ],
    },
    {
      id: "children-info",
      title: "Child/Children Information",
      fields: [
        { id: "child1Name", label: "Child 1 full legal name", type: "text" },
        {
          id: "child1Sex",
          label: "Child 1 sex",
          type: "select",
          options: [
            { label: "M", value: "M" },
            { label: "F", value: "F" },
          ],
        },
        { id: "child1Dob", label: "Child 1 date of birth", type: "date" },
        { id: "child1PlaceOfBirth", label: "Child 1 place of birth", type: "text" },
        { id: "child1Ssn", label: "Child 1 SSN", type: "text" },
        { id: "child1CityCountyState", label: "Child 1 city/county/state of birth", type: "text" },
        { id: "child2Name", label: "Child 2 full legal name", type: "text" },
        {
          id: "child2Sex",
          label: "Child 2 sex",
          type: "select",
          options: [
            { label: "M", value: "M" },
            { label: "F", value: "F" },
          ],
        },
        { id: "child2Dob", label: "Child 2 date of birth", type: "date" },
        { id: "child2PlaceOfBirth", label: "Child 2 place of birth", type: "text" },
        { id: "child2Ssn", label: "Child 2 SSN", type: "text" },
        { id: "child2CityCountyState", label: "Child 2 city/county/state of birth", type: "text" },
        { id: "child3Name", label: "Child 3 full legal name", type: "text" },
        {
          id: "child3Sex",
          label: "Child 3 sex",
          type: "select",
          options: [
            { label: "M", value: "M" },
            { label: "F", value: "F" },
          ],
        },
        { id: "child3Dob", label: "Child 3 date of birth", type: "date" },
        { id: "child3PlaceOfBirth", label: "Child 3 place of birth", type: "text" },
        { id: "child3Ssn", label: "Child 3 SSN", type: "text" },
        { id: "child3CityCountyState", label: "Child 3 city/county/state of birth", type: "text" },
        { id: "child4Name", label: "Child 4 full legal name", type: "text" },
        {
          id: "child4Sex",
          label: "Child 4 sex",
          type: "select",
          options: [
            { label: "M", value: "M" },
            { label: "F", value: "F" },
          ],
        },
        { id: "child4Dob", label: "Child 4 date of birth", type: "date" },
        { id: "child4PlaceOfBirth", label: "Child 4 place of birth", type: "text" },
        { id: "child4Ssn", label: "Child 4 SSN", type: "text" },
        { id: "child4CityCountyState", label: "Child 4 city/county/state of birth", type: "text" },
      ],
    },
    {
      id: "adoptee-info",
      title: "Adoptee Information",
      fields: [
        {
          id: "adopteeRelated",
          label: "Is the child related to you?",
          type: "radio",
          options: [
            { label: "Yes", value: "yes" },
            { label: "No", value: "no" },
          ],
        },
        {
          id: "adopteePrivate",
          label: "Is this a private adoption?",
          type: "radio",
          options: [
            { label: "Yes", value: "yes" },
            { label: "No", value: "no" },
          ],
        },
        {
          id: "adopteeAgency",
          label: "Is this an agency adoption?",
          type: "radio",
          options: [
            { label: "Yes", value: "yes" },
            { label: "No", value: "no" },
          ],
        },
        {
          id: "adopteeOpen",
          label: "Will this be an open adoption?",
          type: "radio",
          options: [
            { label: "Yes", value: "yes" },
            { label: "No", value: "no" },
          ],
        },
        {
          id: "adopteeStepParent",
          label: "Is this a stepparent adoption?",
          type: "radio",
          options: [
            { label: "Yes", value: "yes" },
            { label: "No", value: "no" },
          ],
        },
      ],
    },
    {
      id: "referral",
      title: "Referral Information",
      fields: [
        { id: "referredBy", label: "Referred by", type: "text" },
        {
          id: "referralSource",
          label: "Referral source",
          type: "select",
          options: [
            { label: "Individual", value: "individual" },
            { label: "Website", value: "website" },
            { label: "Internet Search", value: "internet-search" },
            { label: "Former or Current Client", value: "client" },
            { label: "Attorney", value: "attorney" },
            { label: "Radio", value: "radio" },
            { label: "Facebook", value: "facebook" },
            { label: "Therapist", value: "therapist" },
            { label: "TV", value: "tv" },
            { label: "Other", value: "other" },
          ],
        },
        {
          id: "referralOther",
          label: "Other referral source",
          type: "text",
          showIf: { fieldId: "referralSource", equals: "other" },
        },
      ],
    },
  ],
};
