import { IntakeDef, FieldDef } from "../engine/types";

const childFields = (index: number): FieldDef[] => [
  { id: `child${index}Name`, label: `Child ${index} full legal name`, type: "text" },
  {
    id: `child${index}Sex`,
    label: `Child ${index} sex`,
    type: "select",
    options: [
      { label: "M", value: "M" },
      { label: "F", value: "F" },
    ],
  },
  { id: `child${index}Dob`, label: `Child ${index} date of birth`, type: "date" },
  { id: `child${index}PlaceOfBirth`, label: `Child ${index} place of birth`, type: "text" },
  { id: `child${index}Ssn`, label: `Child ${index} SSN`, type: "text" },
  { id: `child${index}CityCountyState`, label: `Child ${index} city/county/state of birth`, type: "text" },
];

export const mediationIntake: IntakeDef = {
  intakeType: "mediation",
  title: "Client Intake: Mediation",
  description: "Information about your mediation matter.",
  steps: [
    {
      id: "your-info",
      title: "Your Information",
      fields: [
        { id: "yourFirstName", label: "First name", type: "text", required: true },
        { id: "yourMiddleName", label: "Middle name", type: "text" },
        { id: "yourLastName", label: "Last name", type: "text", required: true },
        { id: "yourBirthName", label: "Birth/Maiden name", type: "text" },
        { id: "yourStreet", label: "Street address", type: "text" },
        { id: "yourCity", label: "City", type: "text" },
        { id: "yourState", label: "State", type: "text" },
        { id: "yourZip", label: "Zip code", type: "text" },
        { id: "yourCounty", label: "County", type: "text" },
        { id: "yourCountyDuration", label: "How long in this county?", type: "text" },
        { id: "yourHomePhone", label: "Home phone", type: "tel" },
        { id: "yourCellPhone", label: "Cell phone", type: "tel" },
        { id: "yourDob", label: "Date of birth", type: "date" },
        { id: "yourPlaceOfBirth", label: "Place of birth", type: "text" },
        { id: "yourSsn", label: "SSN", type: "text" },
        { id: "yourDriversLicense", label: "Driver's license number", type: "text" },
        { id: "yourDriversLicenseState", label: "Issuing state", type: "text" },
        { id: "yourEmployerName", label: "Employer name", type: "text" },
        { id: "yourEmployerAddress", label: "Employer address", type: "text" },
        { id: "yourOccupation", label: "Occupation", type: "text" },
        { id: "yourAnnualIncome", label: "Approximate annual income", type: "text" },
        { id: "yourWorkPhone", label: "Work phone", type: "tel" },
        { id: "yourSafeEmail", label: "Secure/safe email address", type: "email" },
        {
          id: "yourInvoiceEmailOk",
          label: "Email monthly invoices/billing statements as PDF instead of mail?",
          type: "radio",
          options: [
            { label: "Yes", value: "yes" },
            { label: "No", value: "no" },
          ],
        },
        { id: "yourPreferredMailing", label: "Preferred mailing address", type: "text" },
        { id: "yourBillingAddress", label: "Billing address (if different)", type: "text" },
      ],
    },
    {
      id: "opposing-party",
      title: "Opposing Party",
      fields: [
        { id: "opposingFirstName", label: "First name", type: "text" },
        { id: "opposingMiddleName", label: "Middle name", type: "text" },
        { id: "opposingLastName", label: "Last name", type: "text" },
        { id: "opposingBirthName", label: "Birth/Maiden name", type: "text" },
        { id: "opposingStreet", label: "Street address", type: "text" },
        { id: "opposingCity", label: "City", type: "text" },
        { id: "opposingState", label: "State", type: "text" },
        { id: "opposingZip", label: "Zip code", type: "text" },
        { id: "opposingCounty", label: "County", type: "text" },
        { id: "opposingCountyDuration", label: "How long in this county?", type: "text" },
        { id: "opposingHomePhone", label: "Home phone", type: "tel" },
        { id: "opposingCellPhone", label: "Cell phone", type: "tel" },
        { id: "opposingDob", label: "Date of birth", type: "date" },
        { id: "opposingPlaceOfBirth", label: "Place of birth", type: "text" },
        { id: "opposingSsn", label: "SSN", type: "text" },
        { id: "opposingDriversLicense", label: "Driver's license number", type: "text" },
        { id: "opposingDriversLicenseState", label: "Issuing state", type: "text" },
        { id: "opposingEmail", label: "Email address", type: "email" },
        { id: "opposingRace", label: "Race", type: "text" },
        { id: "opposingEmployerAddress", label: "Opposing party's place & address of employment", type: "text" },
        { id: "opposingOccupation", label: "Occupation", type: "text" },
        { id: "opposingAnnualIncome", label: "Approximate annual income", type: "text" },
      ],
    },
    {
      id: "matter-info",
      title: "Information Regarding Matter",
      fields: [
        { id: "matterInDispute", label: "Matter in dispute", type: "textarea" },
        { id: "conflictDate", label: "Date of conflict", type: "date" },
        { id: "conflictPlace", label: "Place of conflict (city/state)", type: "text" },
        { id: "conflictCounty", label: "County", type: "text" },
        {
          id: "activeCase",
          label: "Is there an active case pending?",
          type: "radio",
          options: [
            { label: "Yes", value: "yes" },
            { label: "No", value: "no" },
          ],
        },
        { id: "causeNumber", label: "Cause number", type: "text" },
      ],
    },
    {
      id: "children-info",
      title: "Child/Children Information",
      fields: [
        ...childFields(1),
        ...childFields(2),
        ...childFields(3),
        ...childFields(4),
      ],
    },
    {
      id: "referral",
      title: "Referral Information",
      fields: [
        { id: "referredBy", label: "Referred by", type: "text" },
        {
          id: "referralSource",
          label: "Referral source",
          type: "select",
          options: [
            { label: "Individual", value: "individual" },
            { label: "Website", value: "website" },
            { label: "Internet Search", value: "internet-search" },
            { label: "Former or Current Client", value: "client" },
            { label: "Attorney", value: "attorney" },
            { label: "Radio", value: "radio" },
            { label: "Facebook", value: "facebook" },
            { label: "Therapist", value: "therapist" },
            { label: "TV", value: "tv" },
            { label: "Other", value: "other" },
          ],
        },
        {
          id: "referralOther",
          label: "Other referral source",
          type: "text",
          showIf: { fieldId: "referralSource", equals: "other" },
        },
      ],
    },
  ],
};
