import { IntakeDef } from "../engine/types";

export const prenuptialAgreementIntake: IntakeDef = {
  intakeType: "prenuptial-agreement",
  title: "Client Intake: Prenuptial Agreement",
  description: "Information to prepare your prenuptial agreement.",
  steps: [
    {
      id: "your-info",
      title: "Your Information",
      fields: [
        { id: "yourFirstName", label: "First name", type: "text", required: true },
        { id: "yourMiddleName", label: "Middle name", type: "text" },
        { id: "yourLastName", label: "Last name", type: "text", required: true },
        { id: "yourStreet", label: "Street address", type: "text" },
        { id: "yourCity", label: "City", type: "text" },
        { id: "yourState", label: "State", type: "text" },
        { id: "yourZip", label: "Zip code", type: "text" },
        { id: "yourCounty", label: "County", type: "text" },
        { id: "yourHomePhone", label: "Home phone", type: "tel" },
        { id: "yourCellPhone", label: "Cell phone", type: "tel" },
        { id: "yourEmployerName", label: "Employer name", type: "text" },
        { id: "yourEmployerAddress", label: "Employer address", type: "text" },
        { id: "yourOccupation", label: "Occupation", type: "text" },
        { id: "yourWorkPhone", label: "Work phone", type: "tel" },
        { id: "yourSafeEmail", label: "Secure/safe email address", type: "email" },
        {
          id: "yourInvoiceEmailOk",
          label: "Email monthly invoices/billing statements as PDF instead of mail?",
          type: "radio",
          options: [
            { label: "Yes", value: "yes" },
            { label: "No", value: "no" },
          ],
        },
        { id: "yourPreferredMailing", label: "Preferred mailing address", type: "text" },
        { id: "yourBillingAddress", label: "Billing address (if different)", type: "text" },
      ],
    },
    {
      id: "fiance-info",
      title: "Fiance Information",
      fields: [
        { id: "fianceFirstName", label: "First name", type: "text" },
        { id: "fianceMiddleName", label: "Middle name", type: "text" },
        { id: "fianceLastName", label: "Last name", type: "text" },
        { id: "fianceStreet", label: "Street address", type: "text" },
        { id: "fianceCity", label: "City", type: "text" },
        { id: "fianceState", label: "State", type: "text" },
        { id: "fianceZip", label: "Zip code", type: "text" },
        { id: "fianceCounty", label: "County", type: "text" },
        { id: "fianceHomePhone", label: "Home phone", type: "tel" },
        { id: "fianceCellPhone", label: "Cell phone", type: "tel" },
        { id: "fianceEmployerName", label: "Employer name", type: "text" },
        { id: "fianceEmployerAddress", label: "Employer address", type: "text" },
        { id: "fianceOccupation", label: "Occupation", type: "text" },
        { id: "fianceWorkPhone", label: "Work phone", type: "tel" },
      ],
    },
    {
      id: "marriage-info",
      title: "Marriage Information",
      fields: [
        { id: "marriageDate", label: "Marriage date", type: "date" },
        { id: "marriagePlace", label: "Place of marriage (city/state)", type: "text" },
      ],
    },
    {
      id: "referral",
      title: "Referral Information",
      fields: [
        { id: "referredBy", label: "Referred by", type: "text" },
        {
          id: "referralSource",
          label: "Referral source",
          type: "select",
          options: [
            { label: "Individual", value: "individual" },
            { label: "Website", value: "website" },
            { label: "Internet Search", value: "internet-search" },
            { label: "Former or Current Client", value: "client" },
            { label: "Attorney", value: "attorney" },
            { label: "Radio", value: "radio" },
            { label: "Facebook", value: "facebook" },
            { label: "Therapist", value: "therapist" },
            { label: "TV", value: "tv" },
            { label: "Other", value: "other" },
          ],
        },
        {
          id: "referralOther",
          label: "Other referral source",
          type: "text",
          showIf: { fieldId: "referralSource", equals: "other" },
        },
      ],
    },
  ],
};
